# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Use ubuntu as an image for our build environment
    runs-on: ubuntu-latest
    # What steps does this job consist of?
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      # Setup version 12 of Java
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      # Run all maven phases to deployment
      # with our repository as a target
      - name: Publish jar to GitHub Packages
        run: mvn deploy
        env:
          # Authenticate with GitHub using
          # token from the secrets context
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add distribution env vars
          # used in pom.xml
          DISTRIBUTION_ID: github
          DISTRIBUTION_NAME: Lingo Game project
          DISTRIBUTION_URL: https://maven.pkg.github.com/${{ github.repository }}

  # The job called "package-image"
  package-image:
    # Use ubuntu as an image for our build environment
    runs-on: ubuntu-latest
    # What steps does this job consist of?
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        # Setup version 12 of Java
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
        # Build JAR using maven
      - name: Build jar
        run: mvn package
